// src/js/constants/action-types.js
export const ADD_ARTICLE = 'ADD_ARTICLE'
export const ADD_USER_PROFILE = 'ADD_USER_PROFILE'
export const DATA_LOADED = 'DATA_LOADED'
export const INIT_LINE_CHART = 'INIT_LINE_CHART'
export const SERVE_LINE_DATA = 'SERVE_LINE_DATA'
export const RESET_TIMER = 'RESET_TIMER'
export const UPDATE_YEAR = 'UPDATE_YEAR'
export const INIT_COUNTRY = 'INIT_COUNTRY'
export const ADD_COUNTRY = 'ADD_COUNTRY'
